server:
  port: 8082

spring:
  profiles:
    active: qa
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/bootcamp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: '"Welcome to the departments API"'

---

  spring:
    config:
      activate:
        on-profile: qa
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      password: admin
      url: jdbc:mysql://localhost:3306/bootcamp-qa
      username: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  welcome:
    message: '"Welcome to the departments API"'

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/bootcamp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: '"Welcome to the departments API"'